Initializing Redis Client...
TAP version 14
connected to redis
# Subtest: ✅ Should reset password successfully
    not ok 1 - should be equal
      ---
      compare: ===
      at:
        fileName: src\modules\user\__test__\reset-password.test.ts
        lineNumber: 58
        columnNumber: 7
        isToplevel: true
        generated:
          fileName: src/modules/user/__test__/reset-password.test.ts
          lineNumber: 68
          columnNumber: 7
      stack: |
        src/modules/user/__test__/reset-password.test.ts:58:7
        Generator.next
        fulfilled (src/modules/user/__test__/reset-password.test.ts:5:58)
      source: "test('❌ Should return 404 if user is not found', async (t) => {\r
      
        \  findByEmailStub.returns(null);\r
      
        \  const fastify = build();\r
      
        ------^
      
        \r
      
        \  t.teardown(() => fastify.close());\n"
      diff: |
        --- expected
        +++ actual
        @@ -1,1 +1,1 @@
        -200
        +404
      ...
    
    not ok 2 - should be equivalent
      ---
      diff: |
        --- expected
        +++ actual
        @@ -1,4 +1,5 @@
         Object {
        -  "message": "Password changed successfully",
        -  "status": "success",
        +  "message": "Route POST:/api/v1/auth/reset-password not found",
        +  "error": "Not Found",
        +  "statusCode": 404,
         }
      at:
        fileName: src\modules\user\__test__\reset-password.test.ts
        lineNumber: 59
        columnNumber: 7
        isToplevel: true
        generated:
          fileName: src/modules/user/__test__/reset-password.test.ts
          lineNumber: 69
          columnNumber: 7
      stack: |
        src/modules/user/__test__/reset-password.test.ts:59:7
        Generator.next
        fulfilled (src/modules/user/__test__/reset-password.test.ts:5:58)
      source: "  findByEmailStub.returns(null);\r
      
        \  const fastify = build();\r
      
        \r
      
        \  t.teardown(() => fastify.close());\n"
      ...
    
    1..2
not ok 1 - ✅ Should reset password successfully # time=1990.788ms
  ---
  at:
    fileName: src\modules\user\__test__\reset-password.test.ts
    lineNumber: 42
    columnNumber: 16
    typeName: Object
    generated:
      fileName: src/modules/user/__test__/reset-password.test.ts
      lineNumber: 52
      columnNumber: 16
  source: "    compareOtpStub.restore();\r
  
    \    hashPasswordStub.restore();\r
  
    \    updateUserStub.restore();\r
  
    ---------------^
  
    \    deleteUserOtpStub.restore();\r
  
    \  });\n"
  ...

# Subtest: ❌ Should return 404 if user is not found
    ok 1 - should be equal
    not ok 2 - should be equivalent
      ---
      diff: |
        --- expected
        +++ actual
        @@ -1,3 +1,5 @@
         Object {
        -  "message": "No user found with this email",
        +  "message": "Route POST:/api/v1/auth/reset-password not found",
        +  "error": "Not Found",
        +  "statusCode": 404,
         }
      at:
        fileName: src\modules\user\__test__\reset-password.test.ts
        lineNumber: 71
        columnNumber: 7
        isToplevel: true
        generated:
          fileName: src/modules/user/__test__/reset-password.test.ts
          lineNumber: 81
          columnNumber: 7
      stack: |
        src/modules/user/__test__/reset-password.test.ts:71:7
        Generator.next
        fulfilled (src/modules/user/__test__/reset-password.test.ts:5:58)
      source: "  t.same(response.json(), { message: 'No user found with this email'
        });\r
      
        });\r
      
        \r
      
        test('❌ Should return 400 if password reset request was not made', async (t)
        => {\r
      
        \  findUserWithOtpStub.returns([]);\n"
      ...
    
    1..2
# error thrown in teardown
not ok 2 - ❌ Should return 404 if user is not found # time=1088.977ms
  ---
  at:
    fileName: src\modules\user\__test__\reset-password.test.ts
    lineNumber: 61
    columnNumber: 16
    typeName: Object
    generated:
      fileName: src/modules/user/__test__/reset-password.test.ts
      lineNumber: 71
      columnNumber: 16
  source: "\r
  
    \  t.teardown(() => fastify.close());\r
  
    \r
  
    \  const response = await fastify.inject({\r
  
    \    method: 'POST',\n"
  ...

# Subtest: ❌ Should return 400 if password reset request was not made
    not ok 1 - fastify-plugin: Plugin did not start in time: '@fastify/redis'. You may have forgotten to call 'done' function or to resolve a Promise
      ---
      stack: |
        manageErr (node_modules/fastify/fastify.js:628:33)
        node_modules/fastify/fastify.js:614:11
        Object._encapsulateThreeParam (node_modules/avvio/boot.js:600:7)
        Boot.timeoutCall (node_modules/avvio/boot.js:494:5)
        Boot.callWithCbOrNextTick (node_modules/avvio/boot.js:476:19)
        release (node_modules/fastq/queue.js:171:16)
        Object.resume (node_modules/fastq/queue.js:103:7)
        node_modules/avvio/boot.js:116:18
        node_modules/avvio/boot.js:437:7
        done (node_modules/avvio/lib/plugin.js:226:5)
      at:
        fileName: node_modules\fastify\fastify.js
        lineNumber: 628
        columnNumber: 33
        functionName: manageErr
      type: FastifyError
      code: FST_ERR_PLUGIN_TIMEOUT
      statusCode: 500
      tapCaught: returnedPromiseRejection
      source: |2
              // as cause
              err = err != null && AVVIO_ERRORS_MAP[err.code] != null
                ? appendStackTrace(err, new AVVIO_ERRORS_MAP[err.code](err.message))
        --------------------------------^
                : err
      cause:
        stack: |
          Timeout._onTimeout (node_modules/avvio/lib/plugin.js:114:31)
        at:
          fileName: node_modules\avvio\lib\plugin.js
          lineNumber: 114
          columnNumber: 31
          typeName: Timeout
          methodName: _onTimeout
          functionName: Timeout._onTimeout
        type: FastifyError
        code: AVV_ERR_PLUGIN_EXEC_TIMEOUT
        statusCode: 500
        fn: !class |-
          function fastifyRedis (fastify, options, next) {
            const { namespace, url, closeClient = false, ...redisOptions } = options
      
            let client = options.client || null
      
            if (namespace) {
              if (!fastify.redis) {
                fastify.decorate('redis', Object.create(null))
              }
      
              if (fastify.redis[namespace]) {
                return next(new Error(`Redis '${namespace}' instance namespace has already been registered`))
              }
      
              const closeNamedInstance = (fastify) => {
                return fastify.redis[namespace].quit()
              }
      
              if (client) {
                if (closeClient === true) {
                  fastify.addHook('onClose', closeNamedInstance)
                }
              } else {
                try {
                  if (url) {
                    client = new Redis(url, redisOptions)
                  } else {
                    client = new Redis(redisOptions)
                  }
                } catch (err) {
                  return next(err)
                }
      
                fastify.addHook('onClose', closeNamedInstance)
              }
      
              fastify.redis[namespace] = client
            } else {
              if (fastify.redis) {
                return next(new Error('@fastify/redis has already been registered'))
              } else {
                if (client) {
                  if (closeClient === true) {
                    fastify.addHook('onClose', close)
                  }
                } else {
                  try {
                    if (url) {
                      client = new Redis(url, redisOptions)
                    } else {
                      client = new Redis(redisOptions)
                    }
                  } catch (err) {
                    return next(err)
                  }
      
                  fastify.addHook('onClose', close)
                }
      
                fastify.decorate('redis', client)
              }
            }
      
            // Testing this make the process crash on latest TAP :(
            /* istanbul ignore next */
            const onEnd = function (err) {
              client
                .off('ready', onReady)
                .off('error', onError)
                .off('end', onEnd)
                .quit()
      
              next(err)
            }
      
            const onReady = function () {
              client
                .off('end', onEnd)
                .off('error', onError)
                .off('ready', onReady)
      
              next()
            }
      
            // Testing this make the process crash on latest TAP :(
            /* istanbul ignore next */
            const onError = function (err) {
              if (err.code === 'ENOTFOUND') {
                onEnd(err)
                return
              }
      
              // Swallow network errors to allow ioredis
              // to perform reconnection and emit 'end'
              // event if reconnection eventually
              // fails.
              // Any other errors during startup will
              // trigger the 'end' event.
              if (err instanceof Redis.ReplyError) {
                onEnd(err)
              }
            }
      
            // ioredis provides it in a .status property
            if (client.status === 'ready') {
              // client is already connected, do not register event handlers
              // call next() directly to avoid ERR_AVVIO_PLUGIN_TIMEOUT
              next()
            } else {
              // ready event can still be emitted
              client
                .on('end', onEnd)
                .on('error', onError)
                .on('ready', onReady)
      
              client.ping().catch(onError)
            }
          }
        source: |2
                debug('timed out', name)
                timer = null
                const readyTimeoutErr = new AVV_ERR_PLUGIN_EXEC_TIMEOUT(name)
          ------------------------------^
                // TODO Remove reference to function
                readyTimeoutErr.fn = func
        message: "Plugin did not start in time: '@fastify/redis'. You may have forgotten
          to call 'done' function or to resolve a Promise"
      ...
    
    1..1
# error thrown in teardown
not ok 3 - ❌ Should return 400 if password reset request was not made # time=10050.168ms
  ---
  at:
    fileName: src\modules\user\__test__\reset-password.test.ts
    lineNumber: 73
    columnNumber: 16
    typeName: Object
    generated:
      fileName: src/modules/user/__test__/reset-password.test.ts
      lineNumber: 83
      columnNumber: 16
  source: "\r
  
    test('❌ Should return 400 if password reset request was not made', async (t)
    => {\r
  
    \  findUserWithOtpStub.returns([]);\r
  
    ---------------^
  
    \  const fastify = build();\n"
  ...

# Subtest: ❌ Should return 400 if OTP is expired
    not ok 1 - test unfinished
      ---
      at:
        fileName: src\modules\user\__test__\reset-password.test.ts
        lineNumber: 85
        columnNumber: 16
        typeName: Object
        generated:
          fileName: src/modules/user/__test__/reset-password.test.ts
          lineNumber: 95
          columnNumber: 16
      stack: >
        Object.<anonymous> (src/modules/user/__test__/reset-password.test.ts:85:16)
      
        Module.m._compile [as _compile]
        (node_modules/@isaacs/ts-node-temp-fork-for-pr-2009/dist/index.js:790:29)
        (node_modules/@isaacs/ts-node-temp-fork-for-pr-2009/src/index.ts:1368:23)
      
        Module.m._compile (node_modules/ts-node/dist/index.js:857:29)
        (node_modules/ts-node/src/index.ts:1618:23)
      
        require.extensions.<computed> (node_modules/ts-node/dist/index.js:859:16)
        (node_modules/ts-node/src/index.ts:1621:12)
      
        Object.require.extensions.<computed> [as .ts]
        (node_modules/@isaacs/ts-node-temp-fork-for-pr-2009/dist/index.js:792:16)
        (node_modules/@isaacs/ts-node-temp-fork-for-pr-2009/src/index.ts:1371:12)
      test: ❌ Should return 400 if OTP is expired
      source: "\r
      
        \  t.equal(response.statusCode, 400);\r
      
        \  t.same(response.json(), { message: 'Password reset request has not been
        made.' });\r
      
        ---------------^
      
        });\n"
      ...
    
    1..1
not ok 4 - child test left in queue: ❌ Should return 400 if OTP is invalid
not ok 5 - Connection is closed.
  ---
  stack: |
    EventEmitter.sendCommand (node_modules/ioredis/built/Redis.js:332:28)
    EventEmitter.quit (node_modules/ioredis/built/utils/Commander.js:90:25)
    Object.close (node_modules/@fastify/redis/index.js:126:24)
    Object._encapsulateTwoParam (node_modules/avvio/boot.js:558:13)
    Boot.closeWithCbOrNextTick (node_modules/avvio/boot.js:531:7)
    Task.release (node_modules/fastq/queue.js:171:16)
    worked (node_modules/fastq/queue.js:223:10)
    node_modules/fastify/fastify.js:479:15
  at:
    fileName: node_modules\ioredis\built\Redis.js
    lineNumber: 332
    columnNumber: 28
    typeName: EventEmitter
    methodName: sendCommand
    functionName: EventEmitter.sendCommand
  test: ❌ Should return 404 if user is not found
  source: |2
            }
            if (this.status === "end") {
                command.reject(new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));
    ---------------------------^
                return command.promise;
            }
  ...

not ok 6 - Connection is closed.
  ---
  stack: |
    EventEmitter.sendCommand (node_modules/ioredis/built/Redis.js:332:28)
    EventEmitter.quit (node_modules/ioredis/built/utils/Commander.js:90:25)
    Object.close (node_modules/@fastify/redis/index.js:126:24)
    Object._encapsulateTwoParam (node_modules/avvio/boot.js:558:13)
    Boot.closeWithCbOrNextTick (node_modules/avvio/boot.js:531:7)
    Task.release (node_modules/fastq/queue.js:171:16)
    worked (node_modules/fastq/queue.js:223:10)
    node_modules/fastify/fastify.js:479:15
  at:
    fileName: node_modules\ioredis\built\Redis.js
    lineNumber: 332
    columnNumber: 28
    typeName: EventEmitter
    methodName: sendCommand
    functionName: EventEmitter.sendCommand
  test: ❌ Should return 400 if password reset request was not made
  source: |2
            }
            if (this.status === "end") {
                command.reject(new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));
    ---------------------------^
                return command.promise;
            }
  ...

1..6
