Initializing Redis Client...
TAP version 14
connected to redis
# Subtest: ✅ Should update user successfully
    not ok 1 - should be equal
      ---
      compare: ===
      at:
        fileName: src\modules\user\__test__\update-user.test.ts
        lineNumber: 47
        columnNumber: 7
        isToplevel: true
        generated:
          fileName: src/modules/user/__test__/update-user.test.ts
          lineNumber: 57
          columnNumber: 7
      stack: |
        src/modules/user/__test__/update-user.test.ts:47:7
        Generator.next
        fulfilled (src/modules/user/__test__/update-user.test.ts:5:58)
      source: "      last_name: lastName,\r
      
        \      username,\r
      
        \      id,\r
      
        ------^
      
        \    },\r
      
        \  });\n"
      diff: |
        --- expected
        +++ actual
        @@ -1,1 +1,1 @@
        -200
        +404
      ...
    
    not ok 2 - should be equivalent
      ---
      diff: |
        --- expected
        +++ actual
        @@ -1,9 +1,5 @@
         Object {
        -  "message": "User updated successfully",
        -  "data": Object {
        -    "first_name": "Ladarius",
        -    "last_name": "Grimes",
        -    "username": "Nedra_Baumbach96",
        -    "id": 8,
        -  },
        +  "message": "Route PUT:/api/v1/users/update not found",
        +  "error": "Not Found",
        +  "statusCode": 404,
         }
      at:
        fileName: src\modules\user\__test__\update-user.test.ts
        lineNumber: 48
        columnNumber: 7
        isToplevel: true
        generated:
          fileName: src/modules/user/__test__/update-user.test.ts
          lineNumber: 58
          columnNumber: 7
      stack: |
        src/modules/user/__test__/update-user.test.ts:48:7
        Generator.next
        fulfilled (src/modules/user/__test__/update-user.test.ts:5:58)
      source: "      username,\r
      
        \      id,\r
      
        \    },\r
      
        ------^
      
        \  });\r
      
        });\n"
      ...
    
    1..2
not ok 1 - ✅ Should update user successfully # time=1575.472ms
  ---
  at:
    fileName: src\modules\user\__test__\update-user.test.ts
    lineNumber: 31
    columnNumber: 16
    typeName: Object
    generated:
      fileName: src/modules/user/__test__/update-user.test.ts
      lineNumber: 41
      columnNumber: 16
  source: "  const response = await fastify.inject({\r
  
    \    method: 'PUT',\r
  
    \    url,\r
  
    \    payload: {\r
  
    \      first_name: firstName,\n"
  ...

# Subtest: ❌ Should return 409 if username already exists
    not ok 1 - This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "\#<Object>".
      ---
      stack: >
        UnhandledPromiseRejection: This error originated either by throwing inside of
        an async function without a catch block, or by rejecting a promise which was
        not handled with .catch(). The promise rejected with the reason
        "#<Object>".<anonymous>
      at:
        typeName: 'UnhandledPromiseRejection: This error originated either by throwing
          inside of an async function without a catch block, or by rejecting a promise
          which was not handled with .catch(). The promise rejected with the reason
          "#<Object>"'
        functionName: ""
      type: UnhandledPromiseRejection
      code: ERR_UNHANDLED_REJECTION
      tapCaught: unhandledRejection
      ...
    
    1..1
not ok 2 - ❌ Should return 409 if username already exists # time=47.211ms
  ---
  at:
    fileName: src\modules\user\__test__\update-user.test.ts
    lineNumber: 58
    columnNumber: 16
    typeName: Object
    generated:
      fileName: src/modules/user/__test__/update-user.test.ts
      lineNumber: 68
      columnNumber: 16
  source: "\r
  
    \  t.teardown(() => {\r
  
    \    fastify.close();\r
  
    ---------------^
  
    \    updateUserStub.restore();\r
  
    \  });\n"
  ...

