Initializing Redis Client...
TAP version 14
connected to redis
# Subtest: should verify OTP successfully
    not ok 1 - should be equal
      ---
      compare: ===
      at:
        fileName: src\modules\user\__test__\verify-otp.test.ts
        lineNumber: 40
        columnNumber: 7
        isToplevel: true
        generated:
          fileName: src/modules/user/__test__/verify-otp.test.ts
          lineNumber: 50
          columnNumber: 7
      stack: |
        src/modules/user/__test__/verify-otp.test.ts:40:7
        Generator.next
        fulfilled (src/modules/user/__test__/verify-otp.test.ts:5:58)
      source: "        message: 'User email verified successfully',\r
      
        \        data: { id: validUserId },\r
      
        \    });\r
      
        ------^
      
        });\n"
      diff: |
        --- expected
        +++ actual
        @@ -1,1 +1,1 @@
        -200
        +404
      ...
    
    not ok 2 - should be equivalent
      ---
      diff: |
        --- expected
        +++ actual
        @@ -1,7 +1,5 @@
         Object {
        -  "message": "User email verified successfully",
        -  "status": "verified",
        -  "data": Object {
        -    "id": 62,
        -  },
        +  "message": "Route POST:/auth/verify-otp not found",
        +  "error": "Not Found",
        +  "statusCode": 404,
         }
      at:
        fileName: src\modules\user\__test__\verify-otp.test.ts
        lineNumber: 41
        columnNumber: 7
        isToplevel: true
        generated:
          fileName: src/modules/user/__test__/verify-otp.test.ts
          lineNumber: 51
          columnNumber: 7
      stack: |
        src/modules/user/__test__/verify-otp.test.ts:41:7
        Generator.next
        fulfilled (src/modules/user/__test__/verify-otp.test.ts:5:58)
      source: "        data: { id: validUserId },\r
      
        \    });\r
      
        });\r
      
        \r
      
        test('should return error if OTP is expired', async (t) => {\n"
      ...
    
    1..2
not ok 1 - should verify OTP successfully # time=1336.89ms
  ---
  at:
    fileName: src\modules\user\__test__\verify-otp.test.ts
    lineNumber: 27
    columnNumber: 16
    typeName: Object
    generated:
      fileName: src/modules/user/__test__/verify-otp.test.ts
      lineNumber: 37
      columnNumber: 16
  source: "    ImportMock.mockFunction(UserService, 'compareOtp', true);\r
  
    \    ImportMock.mockFunction(UserService, 'update', verifiedUser);\r
  
    \    ImportMock.mockFunction(UserService, 'deleteUserOtp');\r
  
    ---------------^
  
    \r
  
    \    const response = await fastify.inject({\n"
  ...

# Subtest: should return error if OTP is expired
    not ok 1 - Attempted to wrap findUserWithOtp which is already wrapped
      ---
      stack: >
        checkWrappedMethod
        (node_modules/sinon/lib/sinon/util/core/wrap-method.js:67:21)
      
        wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:132:13)
      
        Function.stub (node_modules/sinon/lib/sinon/stub.js:130:44)
      
        Sandbox.stub (node_modules/sinon/lib/sinon/sandbox.js:454:39)
      
        Function.ImportMock.mockFunction
        (node_modules/ts-mock-imports/src/import-mock.ts:24:37)
      
        src/modules/user/__test__/verify-otp.test.ts:62:6
      
        Generator.next (<anonymous>)
      
        src/modules/user/__test__/verify-otp.test.ts:4:43
      
        new Promise (<anonymous>)
      
        __awaiter (src/modules/user/__test__/verify-otp.test.ts:4:12)
      
        --------------
      
        Error: Stack Trace for original
      
        extendObjectWithWrappedMethods
        (node_modules/sinon/lib/sinon/util/core/wrap-method.js:173:34)
      
        wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:161:5)
      
        Function.stub (node_modules/sinon/lib/sinon/stub.js:130:44)
      
        Sandbox.stub (node_modules/sinon/lib/sinon/sandbox.js:454:39)
      
        Function.ImportMock.mockFunction
        (node_modules/ts-mock-imports/src/import-mock.ts:24:37)
      
        src/modules/user/__test__/verify-otp.test.ts:36:32
      
        Generator.next (<anonymous>)
      
        src/modules/user/__test__/verify-otp.test.ts:4:43
      
        new Promise (<anonymous>)
      
        __awaiter (src/modules/user/__test__/verify-otp.test.ts:4:12)
      at:
        fileName: node_modules\sinon\lib\sinon\util\core\wrap-method.js
        lineNumber: 67
        columnNumber: 21
        functionName: checkWrappedMethod
      type: TypeError
      tapCaught: returnedPromiseRejection
      source: |2
                    );
                } else if (wrappedMethod.restore && wrappedMethod.restore.sinon) {
                    error = new TypeError(
        --------------------^
                        `Attempted to wrap ${valueToString(
                            property,
      ...
    
    1..1
not ok 2 - should return error if OTP is expired # time=30.143ms
  ---
  at:
    fileName: src\modules\user\__test__\verify-otp.test.ts
    lineNumber: 47
    columnNumber: 16
    typeName: Object
    generated:
      fileName: src/modules/user/__test__/verify-otp.test.ts
      lineNumber: 57
      columnNumber: 16
  source: "    t.teardown(() => {\r
  
    \        fastify.close();\r
  
    \    });\r
  
    \r
  
    \    ImportMock.mockFunction(UserService, 'findUserWithOtp',
    expiredOTPRecord);\n"
  ...

# Subtest: should return error if OTP is invalid
    not ok 1 - Attempted to wrap findUserWithOtp which is already wrapped
      ---
      stack: >
        checkWrappedMethod
        (node_modules/sinon/lib/sinon/util/core/wrap-method.js:67:21)
      
        wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:132:13)
      
        Function.stub (node_modules/sinon/lib/sinon/stub.js:130:44)
      
        Sandbox.stub (node_modules/sinon/lib/sinon/sandbox.js:454:39)
      
        Function.ImportMock.mockFunction
        (node_modules/ts-mock-imports/src/import-mock.ts:24:37)
      
        src/modules/user/__test__/verify-otp.test.ts:81:6
      
        Generator.next (<anonymous>)
      
        src/modules/user/__test__/verify-otp.test.ts:4:43
      
        new Promise (<anonymous>)
      
        __awaiter (src/modules/user/__test__/verify-otp.test.ts:4:12)
      
        --------------
      
        Error: Stack Trace for original
      
        extendObjectWithWrappedMethods
        (node_modules/sinon/lib/sinon/util/core/wrap-method.js:173:34)
      
        wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:161:5)
      
        Function.stub (node_modules/sinon/lib/sinon/stub.js:130:44)
      
        Sandbox.stub (node_modules/sinon/lib/sinon/sandbox.js:454:39)
      
        Function.ImportMock.mockFunction
        (node_modules/ts-mock-imports/src/import-mock.ts:24:37)
      
        src/modules/user/__test__/verify-otp.test.ts:36:32
      
        Generator.next (<anonymous>)
      
        src/modules/user/__test__/verify-otp.test.ts:4:43
      
        new Promise (<anonymous>)
      
        __awaiter (src/modules/user/__test__/verify-otp.test.ts:4:12)
      at:
        fileName: node_modules\sinon\lib\sinon\util\core\wrap-method.js
        lineNumber: 67
        columnNumber: 21
        functionName: checkWrappedMethod
      type: TypeError
      tapCaught: returnedPromiseRejection
      source: |2
                    );
                } else if (wrappedMethod.restore && wrappedMethod.restore.sinon) {
                    error = new TypeError(
        --------------------^
                        `Attempted to wrap ${valueToString(
                            property,
      ...
    
    1..1
not ok 3 - should return error if OTP is invalid # time=10.043ms
  ---
  at:
    fileName: src\modules\user\__test__\verify-otp.test.ts
    lineNumber: 61
    columnNumber: 16
    typeName: Object
    generated:
      fileName: src/modules/user/__test__/verify-otp.test.ts
      lineNumber: 71
      columnNumber: 16
  source: "    t.same(JSON.parse(response.body), { message: 'Code has expired.
    Please request again.' });\r
  
    });\r
  
    \r
  
    test('should return error if OTP is invalid', async (t) => {\n"
  ...

# Subtest: should return error if user's account does not exist or is already verified
    not ok 1 - Attempted to wrap findUserWithOtp which is already wrapped
      ---
      stack: >
        checkWrappedMethod
        (node_modules/sinon/lib/sinon/util/core/wrap-method.js:67:21)
      
        wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:132:13)
      
        Function.stub (node_modules/sinon/lib/sinon/stub.js:130:44)
      
        Sandbox.stub (node_modules/sinon/lib/sinon/sandbox.js:454:39)
      
        Function.ImportMock.mockFunction
        (node_modules/ts-mock-imports/src/import-mock.ts:24:37)
      
        src/modules/user/__test__/verify-otp.test.ts:99:4
      
        Generator.next (<anonymous>)
      
        src/modules/user/__test__/verify-otp.test.ts:4:43
      
        new Promise (<anonymous>)
      
        __awaiter (src/modules/user/__test__/verify-otp.test.ts:4:12)
      
        --------------
      
        Error: Stack Trace for original
      
        extendObjectWithWrappedMethods
        (node_modules/sinon/lib/sinon/util/core/wrap-method.js:173:34)
      
        wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:161:5)
      
        Function.stub (node_modules/sinon/lib/sinon/stub.js:130:44)
      
        Sandbox.stub (node_modules/sinon/lib/sinon/sandbox.js:454:39)
      
        Function.ImportMock.mockFunction
        (node_modules/ts-mock-imports/src/import-mock.ts:24:37)
      
        src/modules/user/__test__/verify-otp.test.ts:36:32
      
        Generator.next (<anonymous>)
      
        src/modules/user/__test__/verify-otp.test.ts:4:43
      
        new Promise (<anonymous>)
      
        __awaiter (src/modules/user/__test__/verify-otp.test.ts:4:12)
      at:
        fileName: node_modules\sinon\lib\sinon\util\core\wrap-method.js
        lineNumber: 67
        columnNumber: 21
        functionName: checkWrappedMethod
      type: TypeError
      tapCaught: returnedPromiseRejection
      source: |2
                    );
                } else if (wrappedMethod.restore && wrappedMethod.restore.sinon) {
                    error = new TypeError(
        --------------------^
                        `Attempted to wrap ${valueToString(
                            property,
      ...
    
    1..1
not ok 4 - should return error if user's account does not exist or is already verified # time=7.926ms
  ---
  at:
    fileName: src\modules\user\__test__\verify-otp.test.ts
    lineNumber: 75
    columnNumber: 16
    typeName: Object
    generated:
      fileName: src/modules/user/__test__/verify-otp.test.ts
      lineNumber: 85
      columnNumber: 16
  source: "        url: endpoint,\r
  
    \        payload: { userId: validUserId, otp: validOTP },\r
  
    \    });\r
  
    \r
  
    \    t.equal(response.statusCode, 400);\n"
  ...

# Subtest: should return 500 if an internal error occurs
    not ok 1 - Attempted to wrap findUserWithOtp which is already wrapped
      ---
      stack: >
        checkWrappedMethod
        (node_modules/sinon/lib/sinon/util/core/wrap-method.js:67:21)
      
        wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:132:13)
      
        Function.stub (node_modules/sinon/lib/sinon/stub.js:130:44)
      
        Sandbox.stub (node_modules/sinon/lib/sinon/sandbox.js:454:39)
      
        Function.ImportMock.mockFunction
        (node_modules/ts-mock-imports/src/import-mock.ts:24:37)
      
        src/modules/user/__test__/verify-otp.test.ts:104:34
      
        Generator.next (<anonymous>)
      
        src/modules/user/__test__/verify-otp.test.ts:4:43
      
        new Promise (<anonymous>)
      
        __awaiter (src/modules/user/__test__/verify-otp.test.ts:4:12)
      
        --------------
      
        Error: Stack Trace for original
      
        extendObjectWithWrappedMethods
        (node_modules/sinon/lib/sinon/util/core/wrap-method.js:173:34)
      
        wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:161:5)
      
        Function.stub (node_modules/sinon/lib/sinon/stub.js:130:44)
      
        Sandbox.stub (node_modules/sinon/lib/sinon/sandbox.js:454:39)
      
        Function.ImportMock.mockFunction
        (node_modules/ts-mock-imports/src/import-mock.ts:24:37)
      
        src/modules/user/__test__/verify-otp.test.ts:36:32
      
        Generator.next (<anonymous>)
      
        src/modules/user/__test__/verify-otp.test.ts:4:43
      
        new Promise (<anonymous>)
      
        __awaiter (src/modules/user/__test__/verify-otp.test.ts:4:12)
      at:
        fileName: node_modules\sinon\lib\sinon\util\core\wrap-method.js
        lineNumber: 67
        columnNumber: 21
        functionName: checkWrappedMethod
      type: TypeError
      tapCaught: returnedPromiseRejection
      source: |2
                    );
                } else if (wrappedMethod.restore && wrappedMethod.restore.sinon) {
                    error = new TypeError(
        --------------------^
                        `Attempted to wrap ${valueToString(
                            property,
      ...
    
    1..1
not ok 5 - should return 500 if an internal error occurs # time=11.119ms
  ---
  at:
    fileName: src\modules\user\__test__\verify-otp.test.ts
    lineNumber: 90
    columnNumber: 16
    typeName: Object
    generated:
      fileName: src/modules/user/__test__/verify-otp.test.ts
      lineNumber: 100
      columnNumber: 16
  source: "\r
  
    \    const response = await fastify.inject({\r
  
    \        method: 'POST',\r
  
    ---------------^
  
    \        url: endpoint,\r
  
    \        payload: { userId: validUserId, otp: validOTP },\n"
  ...

